#!/usr/bin/python3
import sys


def readFile(path: str):
    with open(path, 'r') as f:
        content = f.readlines()
    return content


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Provide path to file to reflect.')
        sys.exit(1)

    filepath = sys.argv[1]
    print(readFile(filepath))
